# Generated by Django 5.1.6 on 2025-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("incident_id", models.AutoField(primary_key=True, serialize=False)),
                ("machine_ip", models.CharField(db_index=True, max_length=100)),
                ("type_of_parameter", models.CharField(max_length=10)),
                ("value_of_parameter", models.CharField(max_length=10)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "db_table": "incident_storage",
            },
        ),
    ]
