# Generated by Django 5.1.6 on 2025-02-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetricStorage",
            fields=[
                ("metric_id", models.AutoField(primary_key=True, serialize=False)),
                ("machine_ip", models.CharField(db_index=True, max_length=30)),
                ("cpu", models.CharField(max_length=10)),
                ("mem", models.CharField(max_length=10)),
                ("disk", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("uptime", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "metric_storage",
            },
        ),
    ]
